# Generated by Django 6.0.7 on 2026-07-14 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 7, 14, 10, 45, 53, 231165, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
