# Generated by Django 6.0.7 on 2026-08-12 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.DateField(default=datetime.date(2026, 8, 12)),
        ),
    ]
