# Generated by Django 6.0.7 on 2026-08-12 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 8, 12, 3, 43, 59, 438320, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
