# Generated by Django 6.0.7 on 2026-08-12 03:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
