# Generated by Django 6.0.7 on 2026-08-14 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.DateField(default=datetime.date(2026, 8, 14)),
        ),
    ]
