# Generated by Django 6.0.7 on 2026-08-15 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.DateField(default=datetime.date(2026, 8, 15)),
        ),
    ]
